#define Create_0
/*"/*'/**//* YYD ACTION
lib_id=1
action_id=603
applies_to=self
*/
currentPage=1
image_alpha=0

photoX=240
photoY=99
textAX=25
textAY=175
textBX=25
textBY=49
#define Step_0
/*"/*'/**//* YYD ACTION
lib_id=1
action_id=603
applies_to=self
*/
if oKeyCodes.kCodePressed[5]=1
{
  if currentPage>1
  {
    playSound(global.snd_PageFlip,0,0.95,1)
    image_alpha=0
    currentPage-=1
  }
}
if oKeyCodes.kCodePressed[6]=1 or keyboard_check_pressed(vk_enter)
{
  if currentPage<13 {playSound(global.snd_PageFlip,0,0.95,1)}
  image_alpha=0
  currentPage+=1
  if currentPage=14
  {
    room_goto(rTitle)
  }
}
else if oKeyCodes.kCodePressed[7]=1
{
  room_goto(rTitle)
}

if image_alpha<1 {image_alpha+=0.025}
#define Draw_0
/*"/*'/**//* YYD ACTION
lib_id=1
action_id=603
applies_to=self
*/
draw_set_alpha(1)
draw_set_color(make_color_rgb(248,248,248))
draw_set_halign(fa_left)
draw_set_font(fnt_EnemyChat)
draw_text(4,4,string("Press [K] or [Enter] to go forward one page or [J] to go back. Press [L] to go back to the title screen.#Page: ") +string(currentPage) +string("/13"))

draw_set_font(fnt_NES)
draw_set_alpha(image_alpha)
if currentPage=1
{
  draw_sprite_ext(sSSF_Pages,0,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"JERRY AND JEREMY WERE TWO GAMERS LIKE MANY OTHERS.#
THOUGH LIFE HAD TAKEN HOLD OF THEIR ACTIVITIES, THEY#
STILL MADE TIME FOR GAMING.#

ONE DAY THOUGH, WHILE RAIDING SOMEONE’S SECOND LIFE#
HEADQUARTERS, THE TWO FOUND THEMSELVES PULLED INTO#
A WORLD LIKE MANY THEY HAD SEEN BEFORE.")
}
else if currentPage=2
{
  draw_sprite_ext(sSSF_Pages,1,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"JERRY AND JEREMY WERE THROWN INTO A WORLD OF WHAT#
LOOKED LIKE GAMES THEY HAD PLAYED. JERRY FOUND HIMSELF#
PITTED AGAINST MANY OBSTACLES. JEREMY HAD BEEN PLACED#
IN A FORTUNATE PLACE TO ASSIST JERRY VIA BEING ABLE#
TO MODIFY THE WORLD IN CERTAIN WAYS.#

THE TWO KEPT SEARCHING THE WORLD, HOPING TO FIND A WAY#
BACK HOME.")
}
else if currentPage=3
{
  draw_sprite_ext(sSSF_Pages,2,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"THE TWO FOUND OUT THAT OTHERS FROM THE REAL WORLD HAD#
ALSO SHOWN UP IN THIS VIDEO GAME LIKE PLACE. THEN UPON#
FURTHER INVESTIGATION, JEREMY HAD CONFIRMED THAT THEY#
HAD SOMEHOW BEEN THROWN INTO A COMPUTER SIMULATION#
CALLED ‘THE DARKNESS’, A PIECE OF SOFTWARE DESIGNED TO#
PROCEDURALLY CREATE LARGE GAME WORLDS AND SET RULES#
FOR THEM.")
}
else if currentPage=4
{
  draw_sprite_ext(sSSF_Pages,3,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"THE TWO GAMERS THEN FOUND OUT THAT THE PROGRAM’S#
DESIGNERS HAD ALSO BEEN SUCKED INTO IT. THEY FOUND#
‘THE ARTIST’, THE HEAD OF THE PROJECT, HIDING HIMSELF.#
HE TOLD THEM THAT IF THEY FIND ALL 7 OF THE DATA#
REALLOCATION MODULES, (WHICH TOOK THE FORM OF MUFFINS)#
THEY WOULD BE ABLE TO SHUT THE PROGRAM DOWN AND FREE#
EVERYONE FROM IT.")
}
else if currentPage=5
{
  draw_sprite_ext(sSSF_Pages,4,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"THE PROGRAM RESPONDED TO THE TWO GAMERS TRYING TO FIND#
THE MUFFIN SHAPED MODULES, AND TRIED TO STOP THEM.#
IT ALSO CREATED A NEW ENTITY IN THE PROGRAM#
NAMED HEXOR TO COUNTER JEREMY’S HACKING OF#
THE SOFTWARE. DESPITE EVERY EFFORT THE PROGRAM HAD#
IN TRYING TO STOP JERRY AND JEREMY, IT WAS NOT#
ENOUGH FOR THEIR VIDEO GAME SAVVY WAYS.")
}
else if currentPage=6
{
  draw_sprite_ext(sSSF_Pages,5,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"THE PROGRAM RESPONDED AGAIN BY MAKING A DESPERATE MOVE.#
IT ATTACKED A TOWN THAT HAD BEEN ESTABLISHED BY A FEW#
THAT HAD BEEN THROWN INTO THE PROGRAM.#

UPON JERRY AND JEREMY RETURNING TO THE TOWN WITH ONLY#
ONE MUFFIN LEFT TO FIND, THEY FOUND THAT EVERYONE WAS#
TAKEN TO A SECURE LOCATION, INCLUDING THE ARTIST.#

HOWEVER, THERE WAS ONE PERSON STILL LEFT.")
}
else if currentPage=7
{
  draw_sprite_ext(sSSF_Pages,6,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"SOMEONE WHO THE TWO HAD MET BEFORE WHO WENT BY THE NAME#
‘FLAME INSTIGATOR’ WAS IN FACT, THE LEAD ENGINEER ON#
THE PROJECT OF ‘THE DARKNESS.’ HE TOLD THEM THAT SINCE#
THE PROGRAM NOW HAD THE ARTIST IN CONTROL, THAT IT#
WOULD THEN BE ABLE TO GAIN FULL CONTROL OF ITSELF#
AND SET RULES TO ENSLAVE EVERYONE IN THE SYSTEM.")
}
else if currentPage=8
{
  draw_sprite_ext(sSSF_Pages,7,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"UPON REACHING THE ARTIST, THE PROGRAM TOLD THEM THAT#
THE MUFFINS COULD BE USED TO SHUT IT ALL DOWN BUT#
DOING SO WOULD KILL EVERYONE WITHIN IT. JEREMY CAME TO#
AN AGREEMENT WITH THE PROGRAM. IF JERRY COULD DEFEAT#
THE PROGRAM’S CHAMPION, THE PROGRAM WOULD BACK AWAY AND#
LET HUMANS WITHIN IT BE FREE, BUT IF JERRY SHOULD FAIL,#
THEY WOULD HAVE TO HAND OVER THE MUFFINS. THEY LET#
THE ARTIST HOLD THEM WHILE THE VICTOR WAS DECIDED IN#
AN EPIC BATTLE. (THROUGH MANY MANY GAME OVERS BY THOSE#
THAT PLAYED THE FIRST DISTORTED TRAVESTY.)")
}
else if currentPage=9
{
  draw_sprite_ext(sSSF_Pages,8,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"JERRY WAS VICTORIOUS AND THE PROGRAM UPHELD ITS END OF#
THE AGREEMENT. HOWEVER, THE ARTIST HAD OTHER IDEAS.#
HE TOOK THE MUFFINS AND HEADED TO A SPECIFIC LOCATION#
TO USE THE MUFFINS TO SHUT THE PROGRAM DOWN. THE#
PROGRAM THEN ASSISTED JERRY AND JEREMY IN STOPPING#
THE ARTIST. HOWEVER, THE BOT, HEXOR WAS ALSO#
ASSISTING THE ARTIST.")
}
else if currentPage=10
{
  draw_text(textBX,textBY,"JERRY FOUGHT AGAINST THE ARTIST WHILE JEREMY KEPT#
BACK HEXOR’S ATTEMPTS TO STOP JERRY. THE ARTIST MADE#
HIMSELF INVINCIBILE WITH THE MUFFINS, THAT IS UNTIL#
JERRY DESTROYED THEM ALL AND EVENTUALLY PREVAILED AS#
THE VICTOR. THE TWO MADE A QUICK ESCAPE FROM THE AREA#
AND JEREMY REMOVED THE BOT, HEXOR.#

HOWEVER, IN DESTROYING THE MUFFINS, THE PROGRAM NO#
LONGER WAS ABLE TO REGAIN FULL CONTROL OF THE SYSTEM.#
IT WAS THEN RELEGATED TO OVERWATCHING THE WORLD AND#
KEEPING CERTAIN HARMFUL BOTS AT BAY.#

EVERYTHING SEEMED FINE IN THE WORLD UNTIL THE PROGRAM#
STOPPED RESPONDING TO ANYONE WITHIN IT. FURTHERMORE,#
A DISTURBANCE WAS FOUND ON AN ISLAND.")
}
else if currentPage=11
{
  draw_sprite_ext(sSSF_Pages,9,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"CLAIRE AND HER HACKER FRIEND, CHAO, WENT TO GO#
INVESTIGATE THE DISTURBANCE. THEY SOON FOUND THAT JERRY#
AND JEREMY WERE ALSO ON THE ISLAND. JERRY AND CLAIRE#
HAVING A SHAKEY PAST, HAD VERBAL CLASHINGS.#
MEANWHILE, CHAO WAS HAPPY TO SEE HER BROTHER, JEREMY#
AFTER SO LONG.#

THE REUNION WASN’T A HAPPY ONE, AS THE FOUR FOUND OUT#
THAT A VIRUS HAD STRUCK THE SYSTEM, CAUSING THE PROGRAM#
TO NOT RESPOND.")
}
else if currentPage=12
{
  draw_sprite_ext(sSSF_Pages,10,photoX,photoY,1,1,0,c_white,image_alpha)
  draw_text(textAX,textAY,"THEY SET OUT TO REMOVE THE VIRUS, HOWEVER, THE VIRUS HAD#
A ONE UP ON THEM. IT HAD KNOWN ENOUGH TO LURE THESE#
GAMERS TO THE ISLAND AS A DECOY WHILE IT ATTACKED THE#
VARIOUS FUNCTIONS OF THE PROGRAM.#

THE PROGRAM NOW HAD NO WAY OF ACTIVELY DICTATING WHAT#
WAS HAPPENING IN THE WORLD AND NO WAY TO REMOVE THE#
VIRUS ITSELF. ONLY ITS PASSIVE FUNCTIONS SUCH AS WORLD#
STABILITY WERE ACTIVE NOW.")
}
else if currentPage=13
{
  draw_text(textBX,textBY,"THE FOUR SAW AS THE VIRUS BEGAN ITS CONTROL OF THE#
SYSTEM, INFECTING BOTS WITH THE SYSTEM AS WELL, TURNING#
THEM ON OTHER BOTS AND HUMANS WITHIN THE WORLD.#

ALL LOOKED HOPELESS UNTIL JEREMY HAD A PLAN TO#
STRIKE BACK AND REMOVE THE VIRUS, THEREBY BRINGING#
THE PROGRAM BACK IN CONTROL.#

BUT WOULD JEREMY’S PLAN BE ENOUGH TO BRING THE SYSTEM#
BACK? WOULD THE FOUR BE FAST ENOUGH TO STOP THE VIRUS#
BEFORE IT BRINGS DOWN THE WORLD STABILITY FUNCTIONS?#

WE’LL KNOW SOON ENOUGH...")
}
