/*
-- This script is used to load in the external files when the game starts.
-- Total sound files loaded: 183 (+1 Music file)
-- Total music files: 142
*/
loadingBar=0
//============================== MUSIC ==============================
loadingType="Music"
bStream=1
//--------------- Title --------------- 1
global.msc_TitleMenu=SS_LoadSound(working_directory+"\Music\DT_TitleMenu.ogg",bStream)
//--------------- Main Levels --------------- 30
global.msc_Main1=0
global.msc_Main2=0
global.msc_Main3=0
global.msc_Main4=0
global.msc_NoMain=0
global.msc_CentralCityA=0
global.msc_GamerRun=0
global.msc_LabyrinthRuins=0
global.msc_AncientGateway=0
global.msc_BegoniaTemple=0
global.msc_Farreaches=0
global.msc_Vault=0
global.msc_Barrens=0
global.msc_BurningStretch=0
global.msc_SRDreamer=0
global.msc_NGCLowerChamber=0
global.msc_CityEscape=0
global.msc_GamesNeverDie=0
global.msc_CentralCore=0
global.msc_VirusInfection=0
global.msc_StarrySkies=0
global.msc_WeaponFacility=0
global.msc_TranquilSerenity=0
global.msc_NoControl=0
global.msc_WarshipA=0
global.msc_WarshipB=0
global.msc_HiddenTown=0
global.msc_Discombobulated=0
global.msc_SubconsciousFilter=0
global.msc_MagicalCastle=0
//--------------- Gate Level --------------- 46
//-- Gate 1 -- 6
global.msc_MarioWorld=0
global.msc_MarioUnderground=0
global.msc_MarioCastle1=0
global.msc_MarioCastle2=0
global.msc_MarioCastle3=0
global.msc_MarioClear=0
//-- Gate 2 -- 9
global.msc_ZeldaOverworld=0
global.msc_ZeldaWater=0
global.msc_OminousHall=0
global.msc_ZeldaDunA=0
global.msc_ZeldaDunB=0
global.msc_ZeldaTown=0
global.msc_ZeldasTheme=0
global.msc_DeathMountain=0
global.msc_ZeldaForest=0
//-- Gate 3 -- 7
global.msc_VampireKiller=0
global.msc_SimonsTheme=0
global.msc_HeartOfFire=0
global.msc_MarbleGallery=0
global.msc_CastleCourtyard=0
global.msc_OutOfTime=0
global.msc_ReapersHall=0
//-- Gate 4 -- 12
global.msc_MMIntroStage=0
global.msc_MMBossIntro=0
global.msc_MMVictory=0
global.msc_MMStormEagle=0
global.msc_MMStageSelect=0
global.msc_MMStageIntro=0
global.msc_MMWeaponGet=0
global.msc_MMOverdriveOstrich=0
global.msc_MMToxicJungle=0
global.msc_MMSigmaStage1=0
global.msc_MMSigmaStage2=0
global.msc_MMSigmaStage3=0
//-- Gate 5 -- 5
global.msc_MetMain=0
global.msc_MetBrinstar=0
global.msc_MetNorfair=0
global.msc_MetMaridia=0
global.msc_MetTourian=0
//-- Gate 6 -- 7
global.msc_RPGOverworld=0
global.msc_RPGPlains=0
global.msc_RPGTown=0
global.msc_RPGDoomCastle=0
global.msc_RPGElementsA=0
global.msc_RPGElementsB=0
global.msc_RPGDreamWoods=0
//--------------- Boss --------------- 30
global.msc_BowserFight=0
global.msc_MarioBoss=0
global.msc_ZeldaMiniBoss=0
global.msc_ZeldaBoss=0
global.msc_DanceOfIllusions=0
global.msc_PiercingBattleFury=0
global.msc_DanceWithDeath=0
global.msc_FamiliarFoe=0
global.msc_FinalNightmare=0
global.msc_Encounter=0
global.msc_MMBossFight=0
global.msc_MMEpsilon=0
global.msc_GiantEnemyRobot=0
global.msc_AbominationA=0
global.msc_AbominationB=0
global.msc_AbominationC=0
global.msc_MetRidley=0
global.msc_MetroidBoss=0
global.msc_MetNightmare=0
global.msc_RPGBoss=0
global.msc_OWA=0
global.msc_Sera=0
global.msc_CVBoss=0
global.msc_ChaosBossA=0
global.msc_DarkShadow=0
global.msc_TheBattle=0
global.msc_ChaosWarmaster=0
global.msc_Hatred=0
global.msc_TheExecutive=0
global.msc_ChaosWarmasterEX=0
//--------------- Extra Gates --------------- 6
global.msc_EerieFaces=0
global.msc_GhostlyTheatre=0
global.msc_SacredTemple=0
global.msc_MMCityScape=0
global.msc_ForgottenIsles=0
global.msc_TheHouse=0
//--------------- Misc --------------- 29
global.msc_IFA=0
global.msc_IFB=0
global.msc_IFC=0
global.msc_MonsterRoaming=0
global.msc_SeraBegin=0
global.msc_Starman=0
global.msc_MomentOfTruth=0
global.msc_MasterPlan=0
global.msc_Trivia=0
global.msc_TD=0
global.msc_DarkAmbience=0
global.msc_MarioLavaRoad=0
global.msc_Defective=0
global.msc_FortressSkyguard=0
global.msc_BowserAppears=0
global.msc_IntendedPattern=0
global.msc_TheInstruments=0
global.msc_LastRun=0
global.msc_Credits=0
global.msc_NoneChosen=0
global.msc_BossGallery=0
global.msc_PttT=0
global.msc_ParasiticSeed=0
global.msc_VirusParasite=0
global.msc_Skyfall=0
global.msc_PtHA=0
global.msc_DistortedEncounterA=0
global.msc_Scrolling=0
global.msc_BTBSZ=0

loadingBar+=1
//============================== SOUNDS ==============================
loadingType="Sounds"
bStream=0
//--------------- PLAYER ---------------
//--- general --- 14
global.snd_PlayerJump[0]=SS_LoadSound(working_directory+"\Sound\DT_PlayerJump1.wav",bStream)
global.snd_PlayerJump[1]=SS_LoadSound(working_directory+"\Sound\DT_PlayerJump2.wav",bStream)
global.snd_PlayerJump[2]=SS_LoadSound(working_directory+"\Sound\DT_PlayerJump3.wav",bStream)
global.snd_MarioPipe=SS_LoadSound(working_directory+"\Sound\DT_MarioPipe.wav",bStream)
global.snd_MarioKick=SS_LoadSound(working_directory+"\Sound\DT_MarioKick.wav",bStream)
global.snd_MarioStomp=SS_LoadSound(working_directory+"\Sound\DT_MarioStomp.wav",bStream)
global.snd_MMBeamDown=SS_LoadSound(working_directory+"\Sound\DT_MMBeamDown.wav",bStream)
global.snd_MMBeamUp=SS_LoadSound(working_directory+"\Sound\DT_MMBeamUp.wav",bStream)
global.snd_MMSlide=SS_LoadSound(working_directory+"\Sound\DT_MMSlide.wav",bStream)
global.snd_MMVictoryShine=SS_LoadSound(working_directory+"\Sound\DT_MMVictoryShine.wav",bStream)
global.snd_KirbySuck=SS_LoadSound(working_directory+"\Sound\DT_KirbySuck.wav",bStream)
global.snd_MechStepA=SS_LoadSound(working_directory+"\Sound\DT_MechStepA.wav",bStream)
global.snd_MechStepB=SS_LoadSound(working_directory+"\Sound\DT_MechStepB.wav",bStream)
global.snd_MechJump=SS_LoadSound(working_directory+"\Sound\DT_MechJump.wav",bStream)
global.snd_AirBubble=SS_LoadSound(working_directory+"\Sound\DT_AirBubble.wav",bStream)
global.snd_HookLatch=SS_LoadSound(working_directory+"\Sound\DT_HookLatch.wav",bStream)
global.snd_DashWarn=SS_LoadSound(working_directory+"\Sound\DT_DashWarn.wav",bStream)
global.snd_Chao_Hey=SS_LoadSound(working_directory+"\Sound\DT_Chao_Hey.wav",bStream)
//--- hit --- 1
global.snd_PlayerDamaged[0]=SS_LoadSound(working_directory+"\Sound\DT_PlayerDamaged1.wav",bStream)
//--- death --- 3
global.snd_GameOver=SS_LoadSound(working_directory+"\Sound\DT_GameOver.wav",bStream)
global.snd_Continue=SS_LoadSound(working_directory+"\Sound\DT_Continue.wav",bStream)
global.snd_Retry=SS_LoadSound(working_directory+"\Sound\DT_Retry.wav",bStream)
//--- attack --- 30
global.snd_PlayerAtk[0]=SS_LoadSound(working_directory+"\Sound\DT_PlayerAtk1.wav",bStream)
global.snd_PlayerAtk[1]=SS_LoadSound(working_directory+"\Sound\DT_PlayerAtk2.wav",bStream)
global.snd_PlayerAtk[2]=SS_LoadSound(working_directory+"\Sound\DT_PlayerAtk3.wav",bStream)
global.snd_PlayerAtk[3]=SS_LoadSound(working_directory+"\Sound\DT_PlayerAtk4.wav",bStream)
global.snd_PlayerStrAtk[0]=SS_LoadSound(working_directory+"\Sound\DT_PlayerStrAtk1.wav",bStream)
global.snd_PlayerStrAtk[1]=SS_LoadSound(working_directory+"\Sound\DT_PlayerStrAtk2.wav",bStream)
global.snd_ArrowFling=SS_LoadSound(working_directory+"\Sound\DT_ArrowFling.wav",bStream)
global.snd_ArrowHit=SS_LoadSound(working_directory+"\Sound\DT_ArrowHit.wav",bStream)
global.snd_BombExplode=SS_LoadSound(working_directory+"\Sound\DT_BombExplode.wav",bStream)
global.snd_DaggerHit=SS_LoadSound(working_directory+"\Sound\DT_DaggerHit.wav",bStream)
global.snd_HolyWater=SS_LoadSound(working_directory+"\Sound\DT_HolyWater.wav",bStream)
global.snd_MetroidBomb=SS_LoadSound(working_directory+"\Sound\DT_MetroidBomb.wav",bStream)
global.snd_ComicHit1=SS_LoadSound(working_directory+"\Sound\DT_ComicHit1.wav",bStream)
global.snd_ComicHit2=SS_LoadSound(working_directory+"\Sound\DT_ComicHit2.wav",bStream)
global.snd_ComicHit3=SS_LoadSound(working_directory+"\Sound\DT_ComicHit3.wav",bStream)
global.snd_MMBuster[0]=SS_LoadSound(working_directory+"\Sound\DT_MMBuster1.wav",bStream)
global.snd_MMBuster[1]=SS_LoadSound(working_directory+"\Sound\DT_MMBuster2.wav",bStream)
global.snd_MMBuster[2]=SS_LoadSound(working_directory+"\Sound\DT_MMBuster3.wav",bStream)
global.snd_MetShotA=SS_LoadSound(working_directory+"\Sound\DT_MetShotA.wav",bStream)
global.snd_MetShotB=SS_LoadSound(working_directory+"\Sound\DT_MetShotB.wav",bStream)
global.snd_MetMissile=SS_LoadSound(working_directory+"\Sound\DT_MetMissile.wav",bStream)
global.snd_MorphBomb=SS_LoadSound(working_directory+"\Sound\DT_MorphBomb.wav",bStream)
global.snd_LinkBomb=SS_LoadSound(working_directory+"\Sound\DT_LinkBomb.wav",bStream)
global.snd_HolyWaterThrow=SS_LoadSound(working_directory+"\Sound\DT_HolyWaterThrow.wav",bStream)
global.snd_GravityShot=SS_LoadSound(working_directory+"\Sound\DT_GravityShot.wav",bStream)
global.snd_IceGunShot=SS_LoadSound(working_directory+"\Sound\DT_IceGunShot.wav",bStream)
global.snd_IceGunSplit=SS_LoadSound(working_directory+"\Sound\DT_IceGunSplit.wav",bStream)
global.snd_WepCharge=SS_LoadSound(working_directory+"\Sound\DT_WepCharge.wav",bStream)
global.snd_WepChargeComplete=SS_LoadSound(working_directory+"\Sound\DT_WepChargeComplete.wav",bStream)
global.snd_BladeStrike=SS_LoadSound(working_directory+"\Sound\DT_BladeStrike.wav",bStream)
global.snd_SpamShot=SS_LoadSound(working_directory+"\Sound\DT_SpamShot.wav",bStream)
loadingBar+=49
screen_redraw()
//--------------- ENEMY ---------------
//--- attack --- 29
global.snd_MarioCannon=SS_LoadSound(working_directory+"\Sound\DT_MarioCannon.wav",bStream)
global.snd_ThwompHit=SS_LoadSound(working_directory+"\Sound\DT_ThwompHit.wav",bStream)
global.snd_Bobomb=SS_LoadSound(working_directory+"\Sound\DT_Bobomb.wav",bStream)
global.snd_Fireball=SS_LoadSound(working_directory+"\Sound\DT_Fireball.wav",bStream)
global.snd_FireLoop=SS_LoadSound(working_directory+"\Sound\DT_FireLoop.wav",bStream)
global.snd_HardHit1=SS_LoadSound(working_directory+"\Sound\DT_HardHit1.wav",bStream)
global.snd_HardHit2=SS_LoadSound(working_directory+"\Sound\DT_HardHit2.wav",bStream)
global.snd_HardHit3=SS_LoadSound(working_directory+"\Sound\DT_HardHit3.wav",bStream)
global.snd_Flame1=SS_LoadSound(working_directory+"\Sound\DT_Flame1.wav",bStream)
global.snd_Beam=SS_LoadSound(working_directory+"\Sound\DT_Beam.wav",bStream)
global.snd_BombLaunch=SS_LoadSound(working_directory+"\Sound\DT_BombLaunch.wav",bStream)
global.snd_RidleyFire=SS_LoadSound(working_directory+"\Sound\DT_RidleyFire.wav",bStream)
global.snd_CShotA=SS_LoadSound(working_directory+"\Sound\DT_CShotA.wav",bStream)
global.snd_CShotB=SS_LoadSound(working_directory+"\Sound\DT_CShotB.wav",bStream)
global.snd_LaserA=SS_LoadSound(working_directory+"\Sound\DT_LaserA.wav",bStream)
global.snd_LaserB=SS_LoadSound(working_directory+"\Sound\DT_LaserB.wav",bStream)
global.snd_SniperShot=SS_LoadSound(working_directory+"\Sound\DT_SniperShot.wav",bStream)
global.snd_Wave=SS_LoadSound(working_directory+"\Sound\DT_Wave.wav",bStream)
global.snd_Magic=SS_LoadSound(working_directory+"\Sound\DT_Magic.wav",bStream)
global.snd_Shock=SS_LoadSound(working_directory+"\Sound\DT_Shock.wav",bStream)
global.snd_DeathSlash=SS_LoadSound(working_directory+"\Sound\DT_DeathSlash.wav",bStream)
global.snd_ChargeStrike=SS_LoadSound(working_directory+"\Sound\DT_ChargeStrike.wav",bStream)
global.snd_KnightSwordSwing=SS_LoadSound(working_directory+"\Sound\DT_KnightSwordSwing.wav",bStream)
global.snd_LightballSpread=SS_LoadSound(working_directory+"\Sound\DT_LightballSpread.wav",bStream)
global.snd_Bite=SS_LoadSound(working_directory+"\Sound\DT_Bite.wav",bStream)
global.snd_IceShot=SS_LoadSound(working_directory+"\Sound\DT_IceShot.wav",bStream)
global.snd_SpearShot=SS_LoadSound(working_directory+"\Sound\DT_SpearShot.wav",bStream)
global.snd_Dec_ChargeUp=SS_LoadSound(working_directory+"\Sound\DT_Dec_ChargeUp.wav",bStream)
global.snd_Dec_Fire=SS_LoadSound(working_directory+"\Sound\DT_Dec_Fire.wav",bStream)
//--- hit --- 4
global.snd_EnemyHit=SS_LoadSound(working_directory+"\Sound\DT_EnemyHit.wav",bStream)
global.snd_EnemyHitZelda=SS_LoadSound(working_directory+"\Sound\DT_EnemyHitZelda.wav",bStream)
global.snd_EnemyHitMM=SS_LoadSound(working_directory+"\Sound\DT_EnemyHitMM.wav",bStream)
global.snd_MetEnemyHitA=SS_LoadSound(working_directory+"\Sound\DT_MetEnemyHitA.wav",bStream)
//--- death --- 5
global.snd_EnemyDie=SS_LoadSound(working_directory+"\Sound\DT_EnemyDie.wav",bStream)
global.snd_EnemyDieZelda=SS_LoadSound(working_directory+"\Sound\DT_EnemyDieZelda.wav",bStream)
global.snd_EnemyDieMM=SS_LoadSound(working_directory+"\Sound\DT_EnemyDieMM.wav",bStream)
global.snd_MetEnemyDieA=SS_LoadSound(working_directory+"\Sound\DT_MetEnemyDieA.wav",bStream)
global.snd_Wilhelm=SS_LoadSound(working_directory+"\Sound\DT_Wilhelm.wav",bStream)
global.snd_RPG_Destroy=SS_LoadSound(working_directory+"\Sound\DT_RPG_Destroy.wav",bStream)
//--- misc --- 20
global.snd_DemonDeath=SS_LoadSound(working_directory+"\Sound\DT_DemonDeath.wav",bStream)
global.snd_DemonLaugh=SS_LoadSound(working_directory+"\Sound\DT_DemonLaugh.wav",bStream)
global.snd_DemonTalk=SS_LoadSound(working_directory+"\Sound\DT_DemonTalk.wav",bStream)
global.snd_DemonVoice1=SS_LoadSound(working_directory+"\Sound\DT_DemonVoice1.wav",bStream)
global.snd_DemonVoice2=SS_LoadSound(working_directory+"\Sound\DT_DemonVoice2.wav",bStream)
global.snd_RidleyScreamA=SS_LoadSound(working_directory+"\Sound\DT_RidleyScreamA.wav",bStream)
global.snd_RidleyScreamB=SS_LoadSound(working_directory+"\Sound\DT_RidleyScreamB.wav",bStream)
global.snd_KraidRoarA=SS_LoadSound(working_directory+"\Sound\DT_KraidRoarA.wav",bStream)
global.snd_MonsterA=SS_LoadSound(working_directory+"\Sound\DT_MonsterA.wav",bStream)
global.snd_VO_Dec_01=SS_LoadSound(working_directory+"\Sound\DT_VO_Dec_01.wav",bStream) //I will divide you by ten
global.snd_VO_Dec_02=SS_LoadSound(working_directory+"\Sound\DT_VO_Dec_02.wav",bStream) //You are not zero
global.snd_VO_Dec_03=SS_LoadSound(working_directory+"\Sound\DT_VO_Dec_03.wav",bStream) //The metric system is superior
global.snd_PortalCreate=SS_LoadSound(working_directory+"\Sound\DT_PortalCreate.wav",bStream)
global.snd_OrbThrow=SS_LoadSound(working_directory+"\Sound\DT_OrbThrow.wav",bStream)
global.snd_Transition=SS_LoadSound(working_directory+"\Sound\DT_Transition.wav",bStream)
global.snd_MetEnemyMove=SS_LoadSound(working_directory+"\Sound\DT_MetEnemyMove.wav",bStream)
global.snd_Charge=SS_LoadSound(working_directory+"\Sound\DT_Charge.wav",bStream)
global.snd_WindBlow=SS_LoadSound(working_directory+"\Sound\DT_WindBlow.wav",bStream)
global.snd_MetGeep=SS_LoadSound(working_directory+"\Sound\DT_MetGeep.wav",bStream)
global.snd_Infect=SS_LoadSound(working_directory+"\Sound\DT_Infect.wav",bStream)
//--- Gate H VO --- 2
global.snd_VO_GH_01=SS_LoadSound(working_directory+"\Sound\DT_VO_GH_01.wav",bStream)
global.snd_VO_GH_02=SS_LoadSound(working_directory+"\Sound\DT_VO_GH_02.wav",bStream)
loadingBar+=55
screen_redraw()
//--------------- GAME STUFF ---------------
//--- Stuff --- 64
global.snd_MoneyPickup=SS_LoadSound(working_directory+"\Sound\DT_MoneyPickup.wav",bStream)
global.snd_HealthPickup=SS_LoadSound(working_directory+"\Sound\DT_HealthPickup.wav",bStream)
global.snd_HealingPlant=SS_LoadSound(working_directory+"\Sound\DT_HealingPlant.wav",bStream)
global.snd_SkillCapsule=SS_LoadSound(working_directory+"\Sound\DT_SkillCapsule.wav",bStream)
global.snd_HeartPiece=SS_LoadSound(working_directory+"\Sound\DT_HeartPiece.wav",bStream)
global.snd_DoorUnlock=SS_LoadSound(working_directory+"\Sound\DT_DoorUnlock.wav",bStream)
global.snd_ChestOpen=SS_LoadSound(working_directory+"\Sound\DT_ChestOpen.wav",bStream)
global.snd_MarioCoin=SS_LoadSound(working_directory+"\Sound\DT_MarioCoin.wav",bStream)
global.snd_MarioBlockBreak=SS_LoadSound(working_directory+"\Sound\DT_MarioBlockBreak.wav",bStream)
global.snd_SpringJump=SS_LoadSound(working_directory+"\Sound\DT_SpringJump.wav",bStream)
global.snd_RBSwitch=SS_LoadSound(working_directory+"\Sound\DT_RBSwitch.wav",bStream)
global.snd_ItemSprout=SS_LoadSound(working_directory+"\Sound\DT_ItemSprout.wav",bStream)
global.snd_PotShatter=SS_LoadSound(working_directory+"\Sound\DT_PotShatter.wav",bStream)
global.snd_MarioFlag=SS_LoadSound(working_directory+"\Sound\DT_MarioFlag.wav",bStream)
global.snd_SwitchHit=SS_LoadSound(working_directory+"\Sound\DT_SwitchHit.wav",bStream)
global.snd_Teleport=SS_LoadSound(working_directory+"\Sound\DT_Teleport.wav",bStream)
global.snd_Error=SS_LoadSound(working_directory+"\Sound\DT_Error.wav",bStream)
global.snd_ZeldaToMap=SS_LoadSound(working_directory+"\Sound\DT_ZeldaToMap.wav",bStream)
global.snd_MMLifeBlip=SS_LoadSound(working_directory+"\Sound\DT_MMLifeBlip.wav",bStream)
global.snd_MMDoorClose=SS_LoadSound(working_directory+"\Sound\DT_MMDoorClose.wav",bStream)
global.snd_MMDoorOpen=SS_LoadSound(working_directory+"\Sound\DT_MMDoorOpen.wav",bStream)
global.snd_MetDoorOpen=SS_LoadSound(working_directory+"\Sound\DT_MetDoorOpen.wav",bStream)
global.snd_MMBulletDeflect=SS_LoadSound(working_directory+"\Sound\DT_MMBulletDeflect.wav",bStream)
global.snd_MMText=SS_LoadSound(working_directory+"\Sound\DT_MMText.wav",bStream)
global.snd_Splash=SS_LoadSound(working_directory+"\Sound\DT_Splash.wav",bStream)
global.snd_Elevator=SS_LoadSound(working_directory+"\Sound\DT_Elevator.wav",bStream)
global.snd_Slam=SS_LoadSound(working_directory+"\Sound\DT_Slam.wav",bStream)
global.snd_Static=SS_LoadSound(working_directory+"\Sound\DT_Static.wav",bStream)
global.snd_Cucco1=SS_LoadSound(working_directory+"\Sound\DT_Cucco1.wav",bStream)
global.snd_Spark=SS_LoadSound(working_directory+"\Sound\DT_Spark.wav",bStream)
global.snd_Alert=SS_LoadSound(working_directory+"\Sound\DT_Alert.wav",bStream)
global.snd_Earthquake=SS_LoadSound(working_directory+"\Sound\DT_Earthquake.wav",bStream)
global.snd_Drip=SS_LoadSound(working_directory+"\Sound\DT_Drip.wav",bStream)
global.snd_ShipMovement=SS_LoadSound(working_directory+"\Sound\DT_ShipMovement.wav",bStream)
global.snd_FadeAway=SS_LoadSound(working_directory+"\Sound\DT_FadeAway.wav",bStream)
global.snd_FireCrackle=SS_LoadSound(working_directory+"\Sound\DT_FireCrackle.wav",bStream)
global.snd_DoorClose=SS_LoadSound(working_directory+"\Sound\DT_DoorClose.wav",bStream)
global.snd_DoorKnock=SS_LoadSound(working_directory+"\Sound\DT_DoorKnock.wav",bStream)
global.snd_DoorOpen=SS_LoadSound(working_directory+"\Sound\DT_DoorOpen.wav",bStream)
global.snd_LampOn=SS_LoadSound(working_directory+"\Sound\DT_LampOn.wav",bStream)
global.snd_ClockTick=SS_LoadSound(working_directory+"\Sound\DT_ClockTick.wav",bStream)
global.snd_FootSteps=SS_LoadSound(working_directory+"\Sound\DT_FootSteps.wav",bStream)
global.snd_CreakySwingA=SS_LoadSound(working_directory+"\Sound\DT_CreakySwingA.wav",bStream)
global.snd_CreakySwingB=SS_LoadSound(working_directory+"\Sound\DT_CreakySwingB.wav",bStream)
global.snd_PageFlip=SS_LoadSound(working_directory+"\Sound\DT_PageFlip.wav",bStream)
global.snd_MMRocks=SS_LoadSound(working_directory+"\Sound\DT_MMRocks.wav",bStream)
global.snd_NewGateTransport=SS_LoadSound(working_directory+"\Sound\DT_NewGateTransport.wav",bStream)
global.snd_RupeeBounce=SS_LoadSound(working_directory+"\Sound\DT_RupeeBounce.wav",bStream)
global.snd_BirdsA=SS_LoadSound(working_directory+"\Sound\DT_BirdsA.wav",bStream)
global.snd_AmmoGrab=SS_LoadSound(working_directory+"\Sound\DT_AmmoGrab.wav",bStream)
global.snd_MMItemGet=SS_LoadSound(working_directory+"\Sound\DT_MMItemGet.wav",bStream)
global.snd_CVItemGet=SS_LoadSound(working_directory+"\Sound\DT_CVItemGet.wav",bStream)
global.snd_MetItemGet=SS_LoadSound(working_directory+"\Sound\DT_MetItemGet.wav",bStream)
global.snd_1up=SS_LoadSound(working_directory+"\Sound\DT_1up.wav",bStream)
global.snd_BoxBreak=SS_LoadSound(working_directory+"\Sound\DT_BoxBreak.wav",bStream)
global.snd_RPG_ItemGrab=SS_LoadSound(working_directory+"\Sound\DT_RPG_ItemGrab.wav",bStream)
global.snd_Thunder=SS_LoadSound(working_directory+"\Sound\DT_Thunder.wav",bStream)
global.snd_MetHealthPickup=SS_LoadSound(working_directory+"\Sound\DT_MetHealthPickup.wav",bStream)
global.snd_ColorPulseA=SS_LoadSound(working_directory+"\Sound\DT_ColorPulseA.wav",bStream)
global.snd_ColorPulseB=SS_LoadSound(working_directory+"\Sound\DT_ColorPulseB.wav",bStream)
global.snd_DistStatic=SS_LoadSound(working_directory+"\Sound\DT_DistStatic.wav",bStream)
global.snd_HitOrb=SS_LoadSound(working_directory+"\Sound\DT_HitOrb.wav",bStream)
global.snd_Secret=SS_LoadSound(working_directory+"\Sound\DT_Secret.wav",bStream)
//--- Unreal Guy --- 19
//kill chains
global.snd_killChain[0]=SS_LoadSound(working_directory+"\Sound\DT_KC_1.wav",bStream)
global.snd_killChain[1]=SS_LoadSound(working_directory+"\Sound\DT_KC_2.wav",bStream)
global.snd_killChain[2]=SS_LoadSound(working_directory+"\Sound\DT_KC_3.wav",bStream)
global.snd_killChain[3]=SS_LoadSound(working_directory+"\Sound\DT_KC_4.wav",bStream)
global.snd_killChain[4]=SS_LoadSound(working_directory+"\Sound\DT_KC_5.wav",bStream)
global.snd_killChain[5]=SS_LoadSound(working_directory+"\Sound\DT_KC_6.wav",bStream)
global.snd_killChain[6]=SS_LoadSound(working_directory+"\Sound\DT_KC_7.wav",bStream)
global.snd_killChain[7]=SS_LoadSound(working_directory+"\Sound\DT_KC_8.wav",bStream)
global.snd_killChain[8]=SS_LoadSound(working_directory+"\Sound\DT_KC_9.wav",bStream)
//killing sprees
global.snd_killingSpree[0]=SS_LoadSound(working_directory+"\Sound\DT_KS_1.wav",bStream)
global.snd_killingSpree[1]=SS_LoadSound(working_directory+"\Sound\DT_KS_2.wav",bStream)
global.snd_killingSpree[2]=SS_LoadSound(working_directory+"\Sound\DT_KS_3.wav",bStream)
global.snd_killingSpree[3]=SS_LoadSound(working_directory+"\Sound\DT_KS_4.wav",bStream)
global.snd_killingSpree[4]=SS_LoadSound(working_directory+"\Sound\DT_KS_5.wav",bStream)
global.snd_killingSpree[5]=SS_LoadSound(working_directory+"\Sound\DT_KS_6.wav",bStream)
global.snd_killingSpree[6]=SS_LoadSound(working_directory+"\Sound\DT_KS_7.wav",bStream)
global.snd_killingSpree[7]=SS_LoadSound(working_directory+"\Sound\DT_KS_8.wav",bStream)
global.snd_killingSpree[8]=SS_LoadSound(working_directory+"\Sound\DT_KS_9.wav",bStream)
global.snd_killingSpree[9]=SS_LoadSound(working_directory+"\Sound\DT_KS_10.wav",bStream)
loadingBar+=83
screen_redraw()
//--------------- MENUS ---------------
global.snd_MenuOpen=SS_LoadSound(working_directory+"\Sound\DT_MenuOpen.wav",bStream)
global.snd_MenuClose=SS_LoadSound(working_directory+"\Sound\DT_MenuClose.wav",bStream)
global.snd_MenuCursor=SS_LoadSound(working_directory+"\Sound\DT_MenuCursor.wav",bStream)
global.snd_MenuConfirm=SS_LoadSound(working_directory+"\Sound\DT_MenuConfirm.wav",bStream)
global.snd_MenuCancel=SS_LoadSound(working_directory+"\Sound\DT_MenuCancel.wav",bStream)
global.snd_MenuShift=SS_LoadSound(working_directory+"\Sound\DT_MenuShift.wav",bStream)
global.snd_InfoOn=SS_LoadSound(working_directory+"\Sound\DT_InfoOn.wav",bStream)
global.snd_InfoOff=SS_LoadSound(working_directory+"\Sound\DT_InfoOff.wav",bStream)
global.snd_SkillGet=SS_LoadSound(working_directory+"\Sound\DT_SkillGet.wav",bStream)
global.snd_MessagePlink=SS_LoadSound(working_directory+"\Sound\DT_MessagePlink.wav",bStream)
global.snd_Recognition=SS_LoadSound(working_directory+"\Sound\DT_Recognition.wav",bStream)
global.snd_Equip=SS_LoadSound(working_directory+"\Sound\DT_Equip.wav",bStream)
global.snd_SaveGame=SS_LoadSound(working_directory+"\Sound\DT_SaveGame.wav",bStream)
global.snd_NewAbilitySet=SS_LoadSound(working_directory+"\Sound\DT_NewAbilitySet.wav",bStream)
loadingBar+=14
screen_redraw()
