ini_open("DT3Options.dts")
var sectionRead,tempVar;

sectionRead="ALPHA"
var tempVar;
global.wearingHatJ=ini_read_real(sectionRead,"147",0)
global.wearingHatC=ini_read_real(sectionRead,"148",0)

global.optMusic=ini_read_real(sectionRead,"201",95)
global.optSound=ini_read_real(sectionRead,"202",95)
global.optShowPointsEarned=ini_read_real(sectionRead,"203",1)
global.optShowDamage=ini_read_real(sectionRead,"204",1)
global.optEnemyHP=ini_read_real(sectionRead,"205",1)
global.optLowHealthWarn=ini_read_real(sectionRead,"206",1)
global.optShowArea=ini_read_real(sectionRead,"207",1)
global.optShowCombatAward=ini_read_real(sectionRead,"208",1)
global.optKeepMenuPos=ini_read_real(sectionRead,"211",0)
global.gamePriority=ini_read_real(sectionRead,"212",0)
global.optVSync=ini_read_real(sectionRead,"213",1)
global.optShowHUD=ini_read_real(sectionRead,"214",1)
global.optCursorRepeat=ini_read_real(sectionRead,"215",3)
global.optAtkTShow=ini_read_real(sectionRead,"217",1)
global.optShowChainMeter=ini_read_real(sectionRead,"218",1)
global.optShowHoverInfo=ini_read_real(sectionRead,"219",0)
global.optSplitWindow=ini_read_real(sectionRead,"220",30)
global.optChaoRoam=ini_read_real(sectionRead,"221",1)
global.optGamePad=ini_read_real(sectionRead,"222",0)
global.optShowKeyState=ini_read_real(sectionRead,"223",0)
global.optWindowSize=ini_read_real(sectionRead,"224",1)
global.optShowScore=ini_read_real(sectionRead,"225",1)
global.optShowMoney=ini_read_real(sectionRead,"226",1)
global.optCentralizeHUD=ini_read_real(sectionRead,"227",0)
global.optMessagePlink=ini_read_real(sectionRead,"228",0)
global.optDPadDash=ini_read_real(sectionRead,"229",1)
global.optRightIsForward=ini_read_real(sectionRead,"230",0)
global.optCanResizeWindow=ini_read_real(sectionRead,"231",1)
global.optUnrealGuyChainAudio=ini_read_real(sectionRead,"232",0)
global.optUnrealGuyChainVisual=ini_read_real(sectionRead,"233",0)
global.optUnrealGuySpreeAudio=ini_read_real(sectionRead,"234",0)
global.optUnrealGuySpreeVisual=ini_read_real(sectionRead,"235",0)
global.optGamepadSetup=ini_read_real(sectionRead,"236",1)
global.optChaoAttack=ini_read_real(sectionRead,"237",0)
global.optShowMapHeader=ini_read_real(sectionRead,"238",0)
global.optBitrateExplosion=ini_read_real(sectionRead,"239",1)
global.optPlayerTrail=ini_read_real(sectionRead,"240",0)
global.optWeaponTrail=ini_read_real(sectionRead,"241",0)
global.optDeathCounter=ini_read_real(sectionRead,"242",0)
global.optUnrealVolume=ini_read_real(sectionRead,"243",100)
global.optUnrealPitch=ini_read_real(sectionRead,"244",1)
global.optNoBounce=ini_read_real(sectionRead,"245",0)
global.optDashWarn=ini_read_real(sectionRead,"246",0)
global.optChaoItemWarn=ini_read_real(sectionRead,"247",1)
global.optMLoop=ini_read_real(sectionRead,"247s",0) // music loop
global.optMorphControls=ini_read_real(sectionRead,"248",1)
global.optSwapType=ini_read_real(sectionRead,"249",0)
global.optStickDeadZone=ini_read_real(sectionRead,"250",0.4)

global.ctrlUp=ini_read_string(sectionRead,"301","W")
global.ctrlDown=ini_read_string(sectionRead,"302","S")
global.ctrlLeft=ini_read_string(sectionRead,"303","A")
global.ctrlRight=ini_read_string(sectionRead,"304","D")
global.ctrlJump=ini_read_string(sectionRead,"305","J")
global.ctrlCharSwap=ini_read_string(sectionRead,"306","U")
global.ctrlAbilSwap=ini_read_string(sectionRead,"307","I")
global.ctrlActA=ini_read_string(sectionRead,"308","K")
global.ctrlActB=ini_read_string(sectionRead,"309","L")
global.ctrlActC=ini_read_string(sectionRead,"310","O")
global.ctrlDashLeft=ini_read_string(sectionRead,"311","Q")
global.ctrlDashRight=ini_read_string(sectionRead,"312","E")

ini_close()
