/*
Saves the options (and hats/controls) to DT3Options.dts, without touching the game save.
Used by saveData and by the Options menu opened from the title screen (oPauseMenu in title mode).
*/
var sectionWrite;
sectionWrite="ALPHA"

ini_open("DT3Options.dts")
ini_write_string("ABOUT","NOTICE","Do not edit this file, doing so will corrupt saved data and cause the game to run incorrectly. Also your save data may be deleted.")

ini_write_real(sectionWrite,"147",global.wearingHatJ)
ini_write_real(sectionWrite,"148",global.wearingHatC)

ini_write_real(sectionWrite,"201",global.optMusic)
ini_write_real(sectionWrite,"202",global.optSound)
ini_write_real(sectionWrite,"203",global.optShowPointsEarned)
ini_write_real(sectionWrite,"204",global.optShowDamage)
ini_write_real(sectionWrite,"205",global.optEnemyHP)
ini_write_real(sectionWrite,"206",global.optLowHealthWarn)
ini_write_real(sectionWrite,"207",global.optShowArea)
ini_write_real(sectionWrite,"208",global.optShowCombatAward)
ini_write_real(sectionWrite,"211",global.optKeepMenuPos)
ini_write_real(sectionWrite,"212",global.gamePriority)
ini_write_real(sectionWrite,"213",global.optVSync)
ini_write_real(sectionWrite,"214",global.optShowHUD)
ini_write_real(sectionWrite,"215",global.optCursorRepeat)
ini_write_real(sectionWrite,"217",global.optAtkTShow)
ini_write_real(sectionWrite,"218",global.optShowChainMeter)
ini_write_real(sectionWrite,"219",global.optShowHoverInfo)
ini_write_real(sectionWrite,"220",global.optSplitWindow)
ini_write_real(sectionWrite,"221",global.optChaoRoam)
ini_write_real(sectionWrite,"222",global.optGamePad)
ini_write_real(sectionWrite,"223",global.optShowKeyState)
ini_write_real(sectionWrite,"224",global.optWindowSize)
ini_write_real(sectionWrite,"225",global.optShowScore)
ini_write_real(sectionWrite,"226",global.optShowMoney)
ini_write_real(sectionWrite,"227",global.optCentralizeHUD)
ini_write_real(sectionWrite,"228",global.optMessagePlink)
ini_write_real(sectionWrite,"229",global.optDPadDash)
ini_write_real(sectionWrite,"230",global.optRightIsForward)
ini_write_real(sectionWrite,"231",global.optCanResizeWindow)
ini_write_real(sectionWrite,"232",global.optUnrealGuyChainAudio)
ini_write_real(sectionWrite,"233",global.optUnrealGuyChainVisual)
ini_write_real(sectionWrite,"234",global.optUnrealGuySpreeAudio)
ini_write_real(sectionWrite,"235",global.optUnrealGuySpreeVisual)
//ini_write_real(sectionWrite,"236",global.optGamepadSetup) //gamepad change: the gamepad presets are gone
ini_write_real(sectionWrite,"237",global.optChaoAttack)
ini_write_real(sectionWrite,"238",global.optShowMapHeader)
ini_write_real(sectionWrite,"239",global.optBitrateExplosion)
ini_write_real(sectionWrite,"240",global.optPlayerTrail)
ini_write_real(sectionWrite,"241",global.optWeaponTrail)
ini_write_real(sectionWrite,"242",global.optDeathCounter)
ini_write_real(sectionWrite,"243",global.optUnrealVolume)
ini_write_real(sectionWrite,"244",global.optUnrealPitch)
ini_write_real(sectionWrite,"245",global.optNoBounce)
ini_write_real(sectionWrite,"246",global.optDashWarn)
ini_write_real(sectionWrite,"247",global.optChaoItemWarn)
ini_write_real(sectionWrite,"247s",global.optMLoop) //music loop
ini_write_real(sectionWrite,"248",global.optMorphControls)
ini_write_real(sectionWrite,"249",global.optSwapType)
ini_write_real(sectionWrite,"250",global.optStickDeadZone)

ini_write_string(sectionWrite,"301",global.ctrlUp)
ini_write_string(sectionWrite,"302",global.ctrlDown)
ini_write_string(sectionWrite,"303",global.ctrlLeft)
ini_write_string(sectionWrite,"304",global.ctrlRight)
ini_write_string(sectionWrite,"305",global.ctrlJump)
ini_write_string(sectionWrite,"306",global.ctrlCharSwap)
ini_write_string(sectionWrite,"307",global.ctrlAbilSwap)
ini_write_string(sectionWrite,"308",global.ctrlActA)
ini_write_string(sectionWrite,"309",global.ctrlActB)
ini_write_string(sectionWrite,"310",global.ctrlActC)
ini_write_string(sectionWrite,"311",global.ctrlDashLeft)
ini_write_string(sectionWrite,"312",global.ctrlDashRight)

//dipswitch change (added): the remaster's dipswitches (see remasterSwitchList)
var i;
remasterSwitchList()
for(i=0;i<global.dsCount;i+=1) {ini_write_real(sectionWrite,global.dsKey[i],variable_global_get(global.dsVar[i]))}

//gamepad change (added): gamepad controls (see loadOptions)
for(i=1;i<=14;i+=1)
{
  if i!=11 and i!=12 {ini_write_real(sectionWrite,string(320+i),global.gpBind[i])}
}

ini_close()
