/*
jukebox change (added): the music room jukebox's list (oJukeboxMenu). Areas are in the order the game reaches them (each
Nightmare Gate where it opens up, after its Access Gate), with their tracks in the order they're first heard. A track
heard in more than one area is listed under the first one.
scrJukeboxAdd(0,name) adds an area name; any other number is the track's findMusic number (9000: the title music).
Not listed: 12 DT_DrumLine and 18 DT_GamesNeverDie (no files), 1023 DT_BossGallery (findMusic looks for
Music\DT_BossGallery.ogg, which isn't there).
*/
jbLines=0
scrJukeboxAdd(0,"Title Screen")
scrJukeboxAdd(9000,"Title Theme")
scrJukeboxAdd(0,"Grand Rising")
scrJukeboxAdd(1,"Main 1")
scrJukeboxAdd(0,"Access Gate 1: Mushroom Kingdom")
scrJukeboxAdd(101,"Mario World")
scrJukeboxAdd(104,"Mario Underground")
scrJukeboxAdd(102,"Mario Castle 1")
scrJukeboxAdd(801,"Bowser Fight")
scrJukeboxAdd(103,"Mario Castle 2")
scrJukeboxAdd(0,"Nightmare Gate A")
scrJukeboxAdd(105,"Mario Castle 3")
scrJukeboxAdd(818,"Mario Boss")
scrJukeboxAdd(0,"Sacred Temple")
scrJukeboxAdd(902,"Sacred Temple")
scrJukeboxAdd(0,"Central City")
scrJukeboxAdd(1014,"Dark Ambience")
scrJukeboxAdd(2,"Central City")
scrJukeboxAdd(3,"Gamer Run")
scrJukeboxAdd(813,"Giant Enemy Robot")
scrJukeboxAdd(0,"Access Gate 2: Hyrule")
scrJukeboxAdd(203,"Zelda Overworld")
scrJukeboxAdd(206,"Zelda Town")
scrJukeboxAdd(204,"Zelda Dungeon A")
scrJukeboxAdd(802,"Zelda Mini Boss")
scrJukeboxAdd(208,"Death Mountain")
scrJukeboxAdd(202,"Ominous Hall")
scrJukeboxAdd(205,"Zelda Dungeon B")
scrJukeboxAdd(201,"Zelda Water")
scrJukeboxAdd(803,"Zelda Boss")
scrJukeboxAdd(209,"Zelda Forest")
scrJukeboxAdd(207,"Zelda's Theme")
scrJukeboxAdd(0,"Nightmare Gate B")
scrJukeboxAdd(901,"Eerie Faces")
scrJukeboxAdd(808,"Final Nightmare")
scrJukeboxAdd(0,"Magical Hills")
scrJukeboxAdd(4,"Main 2")
scrJukeboxAdd(5,"Labyrinth Ruins")
scrJukeboxAdd(0,"Access Gate 3: Transylvania")
scrJukeboxAdd(301,"Vampire Killer")
scrJukeboxAdd(824,"Castlevania Boss")
scrJukeboxAdd(302,"Heart of Fire")
scrJukeboxAdd(303,"Simon's Theme")
scrJukeboxAdd(804,"Dance of Illusions")
scrJukeboxAdd(304,"Marble Gallery")
scrJukeboxAdd(305,"Castle Courtyard")
scrJukeboxAdd(306,"Out of Time")
scrJukeboxAdd(805,"Piercing Battle Fury")
scrJukeboxAdd(307,"Reaper's Hall")
scrJukeboxAdd(806,"Dance with Death")
scrJukeboxAdd(0,"Nightmare Gate C")
scrJukeboxAdd(903,"Ghostly Theatre")
scrJukeboxAdd(0,"Begonia")
scrJukeboxAdd(7,"Main 3")
scrJukeboxAdd(809,"Encounter")
scrJukeboxAdd(8,"Begonia Temple")
scrJukeboxAdd(0,"Access Gate 4: Megapolis")
scrJukeboxAdd(9,"Moment of Truth")
scrJukeboxAdd(401,"Intro Stage")
scrJukeboxAdd(402,"Boss Intro")
scrJukeboxAdd(810,"Boss Fight")
scrJukeboxAdd(403,"Victory")
scrJukeboxAdd(405,"Stage Select")
scrJukeboxAdd(406,"Stage Intro")
scrJukeboxAdd(404,"Storm Eagle")
scrJukeboxAdd(407,"Weapon Get")
scrJukeboxAdd(408,"Overdrive Ostrich")
scrJukeboxAdd(409,"Toxic Jungle")
scrJukeboxAdd(410,"Sigma Stage 1")
scrJukeboxAdd(411,"Sigma Stage 2")
scrJukeboxAdd(412,"Sigma Stage 3")
scrJukeboxAdd(812,"Epsilon")
scrJukeboxAdd(0,"Nightmare Gate D")
scrJukeboxAdd(904,"City Scape")
scrJukeboxAdd(0,"Farreaches")
scrJukeboxAdd(10,"Farreaches")
scrJukeboxAdd(0,"The Vault")
scrJukeboxAdd(11,"The Vault")
scrJukeboxAdd(814,"Abomination A")
scrJukeboxAdd(822,"Abomination B")
scrJukeboxAdd(1001,"IFA")
scrJukeboxAdd(807,"Familiar Foe")
scrJukeboxAdd(1003,"IFC")
scrJukeboxAdd(823,"Abomination C")
scrJukeboxAdd(0,"Barrens")
scrJukeboxAdd(13,"Barrens")
scrJukeboxAdd(0,"Access Gate 5: Research Facility")
scrJukeboxAdd(501,"Metroid Main")
scrJukeboxAdd(502,"Brinstar")
scrJukeboxAdd(816,"Ridley")
scrJukeboxAdd(815,"Metroid Boss")
scrJukeboxAdd(503,"Norfair")
scrJukeboxAdd(504,"Maridia")
scrJukeboxAdd(505,"Tourian")
scrJukeboxAdd(0,"Nightmare Gate F")
scrJukeboxAdd(817,"Metroid Nightmare")
scrJukeboxAdd(0,"Burning Stretch")
scrJukeboxAdd(14,"Burning Stretch")
scrJukeboxAdd(0,"Neo Grime City")
scrJukeboxAdd(15,"Dreamer")
scrJukeboxAdd(16,"Lower Chamber")
scrJukeboxAdd(1004,"Monster Roaming")
scrJukeboxAdd(17,"City Escape")
scrJukeboxAdd(0,"Access Gate 6: Prototype Game")
scrJukeboxAdd(601,"RPG Overworld")
scrJukeboxAdd(603,"RPG Town")
scrJukeboxAdd(602,"RPG Plains")
scrJukeboxAdd(605,"Elements A")
scrJukeboxAdd(819,"RPG Boss")
scrJukeboxAdd(606,"Dream Woods")
scrJukeboxAdd(607,"Elements B")
scrJukeboxAdd(604,"Doom Castle")
scrJukeboxAdd(1011,"Master Plan")
scrJukeboxAdd(1012,"Trivia")
scrJukeboxAdd(0,"Nightmare Gate G")
scrJukeboxAdd(905,"Forgotten Isles")
scrJukeboxAdd(820,"One-Winged Angel")
scrJukeboxAdd(0,"Tower Defense")
scrJukeboxAdd(1013,"Tower Defense")
scrJukeboxAdd(0,"Hidden Program Facility")
scrJukeboxAdd(19,"Central Core")
scrJukeboxAdd(20,"Virus Infection")
scrJukeboxAdd(1005,"Sera Begin")
scrJukeboxAdd(821,"Sera")
scrJukeboxAdd(0,"Starry Skies")
scrJukeboxAdd(21,"Starry Skies")
scrJukeboxAdd(0,"CHAOS Weapons Facility")
scrJukeboxAdd(825,"Chaos Boss A")
scrJukeboxAdd(22,"Weapon Facility")
scrJukeboxAdd(1002,"IFB")
scrJukeboxAdd(0,"Lava Cave")
scrJukeboxAdd(23,"Mario Lava Road")
scrJukeboxAdd(0,"Highlands")
scrJukeboxAdd(24,"Main 4")
scrJukeboxAdd(25,"No Main")
scrJukeboxAdd(1017,"Bowser Appears")
scrJukeboxAdd(0,"Tranquil Serenity")
scrJukeboxAdd(26,"Tranquil Serenity")
scrJukeboxAdd(0,"Hidden Bot Village")
scrJukeboxAdd(27,"Hidden Town")
scrJukeboxAdd(0,"The Discombobulated")
scrJukeboxAdd(28,"Discombobulated")
scrJukeboxAdd(826,"Defective")
scrJukeboxAdd(0,"Displaced Construction Site")
scrJukeboxAdd(6,"Ancient Gateway")
scrJukeboxAdd(827,"Dark Shadow")
scrJukeboxAdd(0,"Subconscious Filter")
scrJukeboxAdd(29,"Subconscious Filter")
scrJukeboxAdd(0,"Magical Castle")
scrJukeboxAdd(30,"Magical Castle")
scrJukeboxAdd(828,"The Battle")
scrJukeboxAdd(0,"Skies of Dragoon")
scrJukeboxAdd(1018,"Intended Pattern")
scrJukeboxAdd(1010,"Fortress Skyguard")
scrJukeboxAdd(0,"Nightmare Gate H")
scrJukeboxAdd(906,"The House")
scrJukeboxAdd(907,"No Control")
scrJukeboxAdd(0,"CHAOS Warship")
scrJukeboxAdd(1015,"Warship A")
scrJukeboxAdd(830,"Hatred")
scrJukeboxAdd(1016,"Warship B")
scrJukeboxAdd(1022,"None Chosen")
scrJukeboxAdd(829,"Chaos Warmaster")
scrJukeboxAdd(1020,"Last Run")
scrJukeboxAdd(1025,"Skyfall")
scrJukeboxAdd(0,"Great Colossal Falloff")
scrJukeboxAdd(1019,"The Instruments")
scrJukeboxAdd(834,"The Executive")
scrJukeboxAdd(832,"Virus Parasite")
scrJukeboxAdd(1024,"PttT")
scrJukeboxAdd(831,"Parasitic Seed")
scrJukeboxAdd(0,"The Distortion")
scrJukeboxAdd(1026,"PtHA")
scrJukeboxAdd(833,"Distorted Encounter")
scrJukeboxAdd(0,"Ending")
scrJukeboxAdd(1021,"Credits")
scrJukeboxAdd(1027,"Scrolling")
scrJukeboxAdd(0,"Bubble Tower Side B")
scrJukeboxAdd(31,"BTBSZ")
scrJukeboxAdd(835,"WEX")
