/*
jukebox change (added): where a music track is from, as "Game [Title]" ("Game [Title (Remixer)]" for a remix, "Artist
[Title]" for an original piece), from the game's music credits (MusicCredits_DT3.txt), the files' own tags and the tracks'
pages. The jukebox (oJukeboxMenu) shows it for the track playing, and the pause menu (oPauseMenu) shows it in the bottom
right. "" if there's none.
argument0: the track's findMusic number (9000: the title music)
*/
switch (argument0)
{
  case 9000: return "XayberOptix [Heroic Kingdom]";
  case 1: return "Zwei!! [Monamo~na]";
  case 2: return "Wild Arms [Adlehyde Castle]";
  case 3: return "T-Free [Video Games]";
  case 4: return "ASMT [World 2]";
  case 5: return "Zwei!! [Ancient Labyrinth Supiri]";
  case 6: return "BlueAngelEagle [Magic Forest]";
  case 7: return "Glover [Atlantis (Ritz190)]";
  case 8: return "Pandemonium! [Skull Fortress]";
  case 9: return "DayDreamingFox [When Dragons Rise]";
  case 10: return "Step [Ecosystem]";
  case 11: return "Final Fantasy IV [Another Moon (Mazedude)]";
  case 13: return "Koori-kun [Desert of Ancient Kings]";
  case 14: return "Contra Force [Stage 1 (NickPerrin)]";
  case 15: return "Streets of Rage 2 [Dreamer (Groovemaster303)]";
  case 16: return "DrMackFoxx [Industrial Ruins]";
  case 17: return "Mega Man X3 [Blast Hornet Stage (Breis)]";
  case 19: return "Mega Man Legends 2 [Mother Zone (ProudOne)]";
  case 20: return "???";
  case 21: return "Metroid Prime [Phendrana Drifts (Beartheshadows)]";
  case 22: return "Xenosaga Episode II [Ormus Stronghold]";
  case 23: return "Super Mario 64 [Koopa's Road (JonnyAtma)]";
  case 24: return "Sonic Adventure [Twinkle Circuit (DrMackFoxx & EspioKaos)]";
  case 25: return "Kevin Leo Smith [Gothic Groove]";
  case 26: return "RabidMedia [Can't Be Real]";
  case 27: return "Wild Arms [Marsh Where the Migrant Birds Gather]";
  case 28: return "F-777 [Crispyness]";
  case 29: return "Mario & Luigi: Dream Team [Dreamy Somnom Woods]";
  case 30: return "Donkey Kong Country 2 [Krook's March]";
  case 31: return "Assassin's Creed [The Bureau]";
  case 101: return "Super Mario Land 2 [Athletic Theme]";
  case 102: return "Super Mario Bros. [Castle Theme]";
  case 103: return "Super Mario World [Castle Theme (Sprittles)]";
  case 104: return "Super Mario Bros. [Underground Theme (sbproductions)]";
  case 105: return "Yoshi's Island [Castle Theme (blackrose96)]";
  case 201: return "Zelda: Ocarina of Time [Water Temple (JakesFable)]";
  case 202: return "Castlevania: Harmony of Despair [Drone]";
  case 203: return "Zelda: Link's Awakening [Overworld (ectsoman)]";
  case 204: return "Zelda II: The Adventure of Link [Palace Theme (DeatHTaX)]";
  case 205: return "Zelda II: The Adventure of Link [Great Palace]";
  case 206: return "Zelda II: The Adventure of Link [Town Theme (DeatHTaX)]";
  case 207: return "The Legend of Zelda [Zelda's Lullaby (smartpoetic)]";
  case 208: return "3D Dot Game Heroes [Advancing Along the Coastline]";
  case 209: return "Zelda: Ocarina of Time [Forest Temple]";
  case 301: return "Castlevania III [Beginning]";
  case 302: return "Castlevania [Heart of Fire (DJ-HappyFace)]";
  case 303: return "Super Castlevania IV [Simon's Theme]";
  case 304: return "Castlevania: Symphony of the Night [Marble Gallery]";
  case 305: return "Castlevania: Symphony of the Night [The Tragic Prince]";
  case 306: return "Castlevania [Out of Time (MusicWizard)]";
  case 307: return "Castlevania: Symphony of the Night [Lost Painting]";
  case 401: return "Mega Man X6 [Infinity Mijinion Stage]";
  case 402: return "Mega Man X [Boss Intro]";
  case 403: return "Mega Man X [Boss Defeated]";
  case 404: return "Mega Man X [Storm Eagle Stage (LennartAlsing)]";
  case 405: return "Mega Man X [Stage Select]";
  case 406: return "Mega Man X [Stage Intro (TritoneAngel)]";
  case 407: return "Mega Man Maverick Hunter X [Get a Weapon]";
  case 408: return "Mega Man X2 [Overdrive Ostrich Stage (Breis)]";
  case 409: return "Mega Man X3 [Gravity Beetle Stage (MetalMetroid)]";
  case 410: return "Mega Man Maverick Hunter X [Sigma Stage 1]";
  case 411: return "Mega Man X2 [X-Hunter Stage 1 (U-GEN)]";
  case 412: return "Mega Man X8 [Sigma Palace]";
  case 501: return "Metroid Fusion [Sector 2 (TRO)]";
  case 502: return "Metroid: Zero Mission [Kraid's Lair]";
  case 503: return "Super Metroid [Lower Norfair (cabose117)]";
  case 504: return "Super Metroid [Maridia (cabose117)]";
  case 505: return "Metroid: Zero Mission [Tourian]";
  case 601: return "Dragon Warrior [Overworld (Bad-Atom)]";
  case 602: return "KFNX [Darnia Field]";
  case 603: return "F4LL0UT [Village in the Wilderness]";
  case 604: return "Lufia & the Fortress of Doom [Sinistrals' Castle (ZombiePosessor)]";
  case 605: return "Phantasy Star II [Rise or Fall (MusicWizard)]";
  case 606: return "DesoloZ [Unexplained Anxiety]";
  case 607: return "Brain Lord [Road to Toronto (Scaredsim)]";
  case 801: return "Super Mario 64 [Koopa's Theme (Jhalkompwdr)]";
  case 802: return "Zelda: The Wind Waker [Miniboss Battle (GenoWhirled)]";
  case 803: return "Zelda: Twilight Princess [Fyrus Battle]";
  case 804: return "Castlevania: Symphony of the Night [Dance of Illusions]";
  case 805: return "Castlevania: Dawn of Sorrow [Piercing Battle Fury]";
  case 806: return "Castlevania Judgment [Evil's Symphonic Poem]";
  case 807: return "Castlevania: Harmony of Despair [Order of the Demon]";
  case 808: return "Zelda: The Minish Cap [Vaati's Wrath]";
  case 809: return "EliteFerrex [Never Stop Fighting!!]";
  case 810: return "Mega Man X3 [Maverick Battle]";
  case 812: return "Mega Man X6 [Vs. Sigma 2]";
  case 813: return "Double Dragon Neon [Boss - Giant Tank]";
  case 814: return "Contra III [The Final Gauntlet, Part 1]";
  case 815: return "Super Metroid [Vs. Kraid (Mozzaratti)]";
  case 816: return "Super Smash Bros. Brawl [Vs. Ridley]";
  case 817: return "Metroid Fusion [Vs. Nightmare (Laikros)]";
  case 818: return "Mario Kart 64 [Bowser's Castle (Miguel Volkov)]";
  case 819: return "Koori-kun [Decisive Battle I]";
  case 820: return "Kingdom Hearts II [One-Winged Angel]";
  case 821: return "Mega Man Legends 2 [Sera Battle (Zero-Resurrected)]";
  case 822: return "Contra III [The Final Gauntlet, Part 2]";
  case 823: return "Contra III [The Final Gauntlet, Part 3]";
  case 824: return "Castlevania Chronicles [Creatures in the Depth]";
  case 825: return "Super Metroid [Mother Brain Battle (Blackaux)]";
  case 826: return "Mattashi [Danger Ahead]";
  case 827: return "Final Fantasy XI [Awakening]";
  case 828: return "Super Smash Bros Melee [How to Play (Guardian Soul)]";
  case 829: return "Wild Arms [Windward Birds (MtB: Rocking Heart)]";
  case 830: return "Sonic CD [Final Fever (ZephyrBurst)]";
  case 831: return "Ys Chronicles [Campanile of Lane]";
  case 832: return "Metroid Prime 3: Corruption [Vs. Rundas]";
  case 833: return "Phantasy Star Online [Pray, for IDOLA the Distorted]";
  case 834: return "Metroid Prime 2: Echoes [Vs. Quadraxis]";
  case 835: return "BlazBlue CentralFiction [YOMOTSUHIRASAKA]";
  case 901: return "Zelda: Link's Awakening [Face Shrine (Charem)]";
  case 902: return "Zelda: Skyward Sword [Fi's Theme]";
  case 903: return "Castlevania: Lament of Innocence [Ghostly Theatre]";
  case 904: return "Mega Man X6 [Gate's Laboratory Stage]";
  case 905: return "The Legend of Dragoon [Volcano Villude]";
  case 906: return "Autumn-Collapse [Whispers of the Past]";
  case 907: return "Peder B. Helland [The Threat]";
  case 1001: return "NGXmusical [Requiem of Innocence]";
  case 1002: return "Wild Arms Alter Code: F [Screaming World]";
  case 1003: return "Xenosaga Episode III [To the Last Place]";
  case 1004: return "F4LL0UT [Humming Lake - Monsters B]";
  case 1005: return "Mega Man Legends 2 [Sera Battle Intro (Zero-Resurrected)]";
  case 1010: return "La-Mulana [Interstice of the Dimension]";
  case 1011: return "Enzer0 [Ode to the Vampire]";
  case 1012: return "Mother 3 [Mr. Saturn Theme]";
  case 1013: return "Assassin's Creed Revelations [Den Defense]";
  case 1014: return "smartpoetic [Dark Ambiance]";
  case 1015: return "Kid2Will [Devastated]";
  case 1016: return "Eschatos [Point of No Return]";
  case 1017: return "Super Mario World [The Evil King Bowser]";
  case 1018: return "Journey to Silius [Stage 1 (Daniel Tidwell)]";
  case 1019: return "Pokemon the Movie 2000 [Lugia's Song (HighwindLegend)]";
  case 1020: return "bassfiddlejones [A Harrowed Heart]";
  case 1021: return "Emil Chronicle Online [Memories]";
  case 1022: return "Wild Arms 3 [A Broken Needle Flowing in the Heart]";
  case 1024: return "Ys Chronicles [Palace]";
  case 1025: return "Xenoblade Chronicles [You Will Know Our Names (MyNewSoundtrack)]";
  case 1026: return "Baten Kaitos [Crystal Abyss]";
  case 1027: return "Wild Arms [Adlehyde Castle]";
}
return "";
