/*
This script is used to stop any sounds that might still be looping.
*/
SS_StopSound(global.snd_PlayerAtk[0])
SS_StopSound(global.snd_PlayerAtk[1])
SS_StopSound(global.snd_PlayerAtk[2])
SS_StopSound(global.snd_PlayerAtk[3])
SS_StopSound(global.snd_PlayerJump[0])
SS_StopSound(global.snd_PlayerDamaged[0])

SS_StopSound(global.snd_MoneyPickup)
SS_StopSound(global.snd_HealthPickup)
SS_StopSound(global.snd_HealingPlant)
SS_StopSound(global.snd_SkillCapsule)
SS_StopSound(global.snd_HeartPiece)
SS_StopSound(global.snd_DoorUnlock)
SS_StopSound(global.snd_ChestOpen)
SS_StopSound(global.snd_SwitchHit)
SS_StopSound(global.snd_MarioCoin)
SS_StopSound(global.snd_RBSwitch)
SS_StopSound(global.snd_GameOver)
SS_StopSound(global.snd_Earthquake)
SS_StopSound(global.snd_FireCrackle)
SS_StopSound(global.snd_DistStatic)

SS_StopSound(global.snd_MenuOpen)
SS_StopSound(global.snd_MenuClose)
SS_StopSound(global.snd_MenuCursor)
SS_StopSound(global.snd_MenuConfirm)
SS_StopSound(global.snd_MenuCancel)
SS_StopSound(global.snd_MenuShift)
SS_StopSound(global.snd_Continue)
SS_StopSound(global.snd_InfoOn)
SS_StopSound(global.snd_InfoOff)
SS_StopSound(global.snd_KirbySuck)
SS_StopSound(global.snd_WepCharge)
